project-1/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/", views.wiki, name="wiki"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("search/", views.search, name="search"), 
    path("wiki/<str:entry>/edit", views.edit, name="edit"), 
    path("create/", views.create, name="create"), 
    path("random/", views.random, name="random")
]

project-1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")), 
]

project-1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project-1/wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse
from django.utils.safestring import mark_safe
from random import randint

from . import util

class EditForm(forms.Form):
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={'class' : 'edit_form'}))

    def clean_content(self):
        content = self.cleaned_data["content"]
        if not content.startswith("# "):
            raise forms.ValidationError("Please start your content with a title hashtag (# Title)")
        return content

class CreateForm(forms.Form):
    title = forms.CharField(label="Page Title", max_length=25)
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={'class' : 'edit_form', 'placeholder': "# Don't Forget Your Page Title\n\nAnd write some awesome content!"}))
    
    def clean_title(self):
        title = self.cleaned_data["title"]
        if title.lower() in [entry.lower() for entry in util.list_entries()]:
            raise forms.ValidationError("A page with this title already exists.")
        return title

    def clean_content(self):
        content = self.cleaned_data["content"]
        if not content.startswith("# "):
            raise forms.ValidationError("Please start your content with a title hashtag (# Title)")
        return content
    
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def wiki(request):
    return HttpResponseRedirect(reverse("wiki:index"))

def entry(request, entry):
    return render(request, "encyclopedia/entry.html", {
        "entry": entry,
        "content": util.markdowner(entry)
    })

def search(request):
    if request.method == "POST":
        q = request.POST['q'].strip()
        matches = []
        for entry in util.list_entries():
            q_low, entry_low = q.lower(), entry.lower()
            if q_low == entry_low:
                return HttpResponseRedirect(reverse("wiki:wiki") + entry)
            if q_low in entry_low:
                matches.append(entry)
        return render(request, "encyclopedia/search.html", {
            "q": q,
            "matches": matches
        })
    return HttpResponseRedirect(reverse("wiki:index"))

def edit(request, entry):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            content = "".join([line for line in form.cleaned_data["content"] if line != "\n"])
            util.save_entry(entry, content)
            return HttpResponseRedirect(reverse("wiki:wiki") + entry) 
        return render(request, "encyclopedia/edit.html", {
            "edit_form": form
        })

    content_body = util.get_entry(entry)
    if not content_body:
        return render(request, "encyclopedia/search.html", {
            "q": entry, 
            "matches": None
        })
    content = {'content': content_body}
    return render(request, "encyclopedia/edit.html", {
        "entry": entry,
        "edit_form": EditForm(initial=content)
    })

def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            lines = "".join([line for line in content if line != "\n"])
            util.save_entry(title, lines)
            return HttpResponseRedirect(reverse("wiki:wiki") + title)
        return render(request, "encyclopedia/create.html", {
            "create_form": form
        })
        
    return render(request, "encyclopedia/create.html", {
        "create_form": CreateForm()
    })

def random(request):
    ls = util.list_entries()
    page = ls[randint(0, len(ls) - 1)]
    return HttpResponseRedirect(reverse("wiki:wiki") + page)

project-1/wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}
{% block title  %}
Create Page
{% endblock title %}
{% block body %}
<h1>Create New Page</h1>
<div class="form">
    <form action="{% url 'wiki:create' %}" method="post">
        {% csrf_token %}
        <p class="field-title">{{ create_form.title.label }}</p>
        {% if not create_form.title.errors %}
        <p class="small-info">Be sure to use a unique title!</p>
        {% else %}
        {{ create_form.title.errors }}
        {% endif %}
        {{ create_form.title }}
        <p class="field-title">{{ create_form.content.label }}</p>
        <p class="small-info">Before writing, check out the <a href="https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax">GitHub Markdown Guide</a>.</p>
        {{ create_form.content.errors }}
        {{ create_form.content }}
        <div class="edit_submit">
            <input type="submit" value="Create" class="btn btn-primary">
        </div>
    </form>
</div>
{% endblock body %}

project-1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
Edit {{ entry }}
{% endblock title %}

{% block body %}
<h1>Edit {{ entry }}</h1>
<div class="form">
    <form action="{% url 'wiki:wiki' %}{{ entry }}/edit" method="post">
        {% csrf_token %}
        <p class="field-title">{{ edit_form.content.label }}</p>
        <p class="small-info">Make your edits here.</p>
        {{ edit_form.content }}
        <div class="edit_submit">
            <input type="submit" class="btn btn-primary">
        </div>
    </form>
</div>
{{ content }}
{% endblock body %}

project-1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ entry }}
{% endblock title %}

{% block body %}
{% if content %}
    {{ content | safe }}
    <a href="{% url 'wiki:wiki' %}{{ entry }}/edit" class="btn btn-light edit_btn">Edit Page</a>
{% else %}
    <h1>Oh no!</h1>
    <p>It looks like this page doesn't exist yet.</p>
    <p>Try creating a <a href="{% url 'wiki:create' %}">New Page</a>!</p>
{% endif %}
{% endblock body %}

project-1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
        <li><a href="wiki/{{entry}}">{{ entry }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

project-1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <link rel="icon" href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/google/274/bug_1f41b.png">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2 class="site-title"><a href="{% url 'wiki:index' %}" class="sidebar-link">Wiki</a></h2>
                <form action="{% url 'wiki:search' %}" method="post" class="search_bar">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search" autocomplete="off">
                </form>
                <div class="sidebar-element">
                    <a class="sidebar-link" href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div class="sidebar-element">
                    <a class="sidebar-link" href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div class="sidebar-element">
                    <a class="sidebar-link" href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                <div class="content">
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>

    </body>
</html>

project-1/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Search
{% endblock title%}

{% block body %}
{% if matches %}
<h1>Results for "{{ q }}"</h1>
<ul>
    {% for match in matches %}
    <li><a href="{% url 'wiki:wiki' %}{{ match }}">{{ match }}</a></li>
    {% endfor %}
</ul>
{% else %}
<h1>Sorry!😔</h1>
<p>No results for "{{ q }}". Try creating a new page!</p>
{% endif %}
{% endblock body %}